# A sample Gemfile
source "https://rubygems.org"

# gem "rails"

#gem 'rails', '4.0.1'

gem 'em-websocket'
gem 'eventmachine'

gem 'json'

gem 'redis'
gem 'hiredis'
gem 'em-synchrony'

gem 'oauth2'
gem 'mysql2' # for search engine

gem 'streamio-ffmpeg'


